/**
 * AQA Lead Deep Data & Equipment Details Helper
 *
 * Encodes and parses deep lead metadata (equipment articles, demographics,
 * acquisition channels, preferences) into the SwimLead.notes field using
 * structured tags and backward-compatible fallback text.
 * Strictly NO emojis and Western Arabic numerals only.
 */

export type EquipmentArticleId = "goggles" | "cap" | "swimsuit";

export interface EquipmentArticleConfig {
  id: EquipmentArticleId;
  label: string;
  shortLabel: string;
  description: string;
}

export const EQUIPMENT_ARTICLES: EquipmentArticleConfig[] = [
  {
    id: "goggles",
    label: "Lunettes de Natation Pro",
    shortLabel: "Lunettes",
    description: "Protection UV400, traitement anti-buee haute performance, pont nasal interchangeable",
  },
  {
    id: "cap",
    label: "Bonnet de Natation Silicone",
    shortLabel: "Bonnet",
    description: "100% silicone hydrodynamique AQA, ergonomique et hypoallergenique",
  },
  {
    id: "swimsuit",
    label: "Maillot / Jammer de Natation",
    shortLabel: "Maillot",
    description: "Tissu technique haute resistance au chlore, coupe compressive et confort durable",
  },
];

export interface SwimLeadEquipment {
  hasPack: boolean;
  articles: EquipmentArticleId[];
  articleLabels: string[];
  rawText?: string | null;
  size?: string | null;
  notes?: string | null;
}

export interface SwimLeadDemographics {
  city?: string | null;
  age?: number | null;
  whatsapp?: string | null;
  channel?: string | null;
  channelOther?: string | null;
  goal?: string | null;
  timePref?: string | null;
  memberType?: "new" | "old" | null;
  personalId?: string | null;
  pool?: string | null;
}

export interface SwimLeadDetails {
  equipment: SwimLeadEquipment;
  demographics: SwimLeadDemographics;
  userNotes: string;
}

const META_TAG_REGEX = /\[AQA_META_START\]([\s\S]*?)\[AQA_META_END\]/;
const LEGACY_META_REGEX = /\[AQA_META:(\{[\s\S]*\})\]/;

/**
 * Normalizes article strings from various sources (e.g. "goggles", "lunettes", "Bonnet", "cap", "swimsuit", "maillot")
 */
export function normalizeArticleId(val: string): EquipmentArticleId | null {
  if (!val) return null;
  const lower = val.toLowerCase().trim();
  if (lower.includes("goggle") || lower.includes("lunette")) return "goggles";
  if (lower.includes("cap") || lower.includes("bonnet")) return "cap";
  if (
    lower.includes("swimsuit") ||
    lower.includes("maillot") ||
    lower.includes("jammer") ||
    lower.includes("combinaison")
  ) {
    return "swimsuit";
  }
  return null;
}

/**
 * Returns human-readable label for an article ID.
 */
export function getArticleLabel(id: EquipmentArticleId): string {
  const cfg = EQUIPMENT_ARTICLES.find((a) => a.id === id);
  return cfg ? cfg.label : id;
}

/**
 * Returns short label for badges in tables.
 */
export function getArticleShortLabel(id: EquipmentArticleId): string {
  const cfg = EQUIPMENT_ARTICLES.find((a) => a.id === id);
  return cfg ? cfg.shortLabel : id;
}

/**
 * Parses raw notes into structured SwimLeadDetails.
 * Seamlessly handles:
 * 1. Modern [AQA_META_START]{...}[AQA_META_END] JSON metadata blocks.
 * 2. Legacy pipe-delimited strings: "Canal: Instagram | WhatsApp: 0550... | Pack Equipement: Oui".
 * 3. Plain unstructured text.
 */
export function parseSwimLeadNotes(notes: string | null | undefined): SwimLeadDetails {
  const defaultDetails: SwimLeadDetails = {
    equipment: {
      hasPack: false,
      articles: [],
      articleLabels: [],
      rawText: null,
      size: null,
      notes: null,
    },
    demographics: {
      city: null,
      age: null,
      whatsapp: null,
      channel: null,
      channelOther: null,
      goal: null,
      timePref: null,
      memberType: null,
      personalId: null,
      pool: null,
    },
    userNotes: "",
  };

  if (!notes || !notes.trim()) {
    return defaultDetails;
  }

  const trimmed = notes.trim();

  // 1. Check for modern structured meta tag or legacy JSON meta
  const metaMatch = trimmed.match(META_TAG_REGEX) || trimmed.match(LEGACY_META_REGEX);
  if (metaMatch && metaMatch[1]) {
    try {
      const parsedMeta = JSON.parse(metaMatch[1]);
      const eq = parsedMeta.equipment || {};
      const demo = parsedMeta.demographics || {};

      const articles: EquipmentArticleId[] = Array.isArray(eq.articles)
        ? (eq.articles.map(normalizeArticleId).filter(Boolean) as EquipmentArticleId[])
        : [];

      // Remove the meta tag from notes to get pure user notes
      let remainingText = trimmed
        .replace(META_TAG_REGEX, "")
        .replace(LEGACY_META_REGEX, "")
        .trim();
      // Also remove any autogenerated legacy human-readable prefix if present
      const humanBlockMatch = remainingText.match(/\[DETAILS_SUMMARY:[\s\S]*?\]/);
      if (humanBlockMatch) {
        remainingText = remainingText.replace(/\[DETAILS_SUMMARY:[\s\S]*?\]/, "").trim();
      }

      return {
        equipment: {
          hasPack: Boolean(eq.hasPack || articles.length > 0),
          articles,
          articleLabels: articles.map(getArticleLabel),
          rawText: eq.rawText || null,
          size: eq.size || null,
          notes: eq.notes || null,
        },
        demographics: {
          city: demo.city || null,
          age: typeof demo.age === "number" ? demo.age : demo.age ? Number(demo.age) : null,
          whatsapp: demo.whatsapp || null,
          channel: demo.channel || null,
          channelOther: demo.channelOther || null,
          goal: demo.goal || null,
          timePref: demo.timePref || null,
          memberType: demo.memberType || null,
          personalId: demo.personalId || null,
          pool: demo.pool || null,
        },
        userNotes: remainingText,
      };
    } catch {
      // Fallback to legacy parser if JSON parsing fails
    }
  }

  // 2. Legacy parser for pipe-delimited or plain text notes
  const details = { ...defaultDetails };
  const articlesSet = new Set<EquipmentArticleId>();
  const unparsedParts: string[] = [];

  const parts = trimmed.split("|").map((p) => p.trim()).filter(Boolean);

  for (const part of parts) {
    const lower = part.toLowerCase();

    if (
      lower.startsWith("pack equipement:") ||
      lower.startsWith("pack équipement:") ||
      lower.startsWith("equipement:") ||
      lower.startsWith("articles:")
    ) {
      details.equipment.hasPack = true;
      const rawVal = part.split(":")[1]?.trim() || "";
      details.equipment.rawText = rawVal;

      if (rawVal.toLowerCase() !== "oui" && rawVal.toLowerCase() !== "yes" && rawVal.toLowerCase() !== "non") {
        const itemTokens = rawVal.split(/[,+]/).map((t) => t.trim());
        for (const token of itemTokens) {
          const norm = normalizeArticleId(token);
          if (norm) articlesSet.add(norm);
        }
      }
    } else if (lower.startsWith("whatsapp:")) {
      details.demographics.whatsapp = part.split(":")[1]?.trim() || null;
    } else if (lower.startsWith("ville:")) {
      details.demographics.city = part.split(":")[1]?.trim() || null;
    } else if (lower.startsWith("age:")) {
      const parsedAge = parseInt(part.split(":")[1]?.trim() || "", 10);
      details.demographics.age = isNaN(parsedAge) ? null : parsedAge;
    } else if (lower.startsWith("canal:")) {
      details.demographics.channel = part.split(":")[1]?.trim() || null;
    } else if (lower.startsWith("objectif:")) {
      details.demographics.goal = part.split(":")[1]?.trim() || null;
    } else if (lower.startsWith("creneau:") || lower.startsWith("créneau:")) {
      details.demographics.timePref = part.split(":")[1]?.trim() || null;
    } else if (lower.startsWith("piscine:")) {
      details.demographics.pool = part.split(":")[1]?.trim() || null;
    } else if (lower.includes("renouvellement ancien membre")) {
      details.demographics.memberType = "old";
      const idMatch = part.match(/\(ID:\s*([^)]+)\)/i);
      if (idMatch && idMatch[1]) {
        details.demographics.personalId = idMatch[1].trim();
      }
    } else {
      unparsedParts.push(part);
    }
  }

  details.equipment.articles = Array.from(articlesSet);
  details.equipment.articleLabels = details.equipment.articles.map(getArticleLabel);
  if (details.equipment.articles.length > 0) {
    details.equipment.hasPack = true;
  }
  details.userNotes = unparsedParts.join(" | ").trim();

  return details;
}

/**
 * Formats structured lead details and user notes into a single string for storage in `SwimLead.notes`.
 * Embeds the [AQA_META:{...}] machine-readable block alongside a human-readable summary.
 */
export function formatSwimLeadNotes(params: {
  equipment?: {
    hasPack?: boolean;
    articles?: EquipmentArticleId[] | string[];
    rawText?: string | null;
    size?: string | null;
    notes?: string | null;
  };
  demographics?: {
    city?: string | null;
    age?: number | string | null;
    whatsapp?: string | null;
    channel?: string | null;
    channelOther?: string | null;
    goal?: string | null;
    timePref?: string | null;
    memberType?: "new" | "old" | null;
    personalId?: string | null;
    pool?: string | null;
  };
  userNotes?: string | null;
}): string {
  const normArticles: EquipmentArticleId[] = (params.equipment?.articles || [])
    .map((a) => normalizeArticleId(String(a)))
    .filter(Boolean) as EquipmentArticleId[];

  const hasPack = Boolean(params.equipment?.hasPack || normArticles.length > 0);

  const cleanDemo: SwimLeadDemographics = {
    city: params.demographics?.city?.trim() || null,
    age:
      typeof params.demographics?.age === "number"
        ? params.demographics.age
        : params.demographics?.age
        ? parseInt(String(params.demographics.age), 10) || null
        : null,
    whatsapp: params.demographics?.whatsapp?.trim() || null,
    channel: params.demographics?.channel?.trim() || null,
    channelOther: params.demographics?.channelOther?.trim() || null,
    goal: params.demographics?.goal?.trim() || null,
    timePref: params.demographics?.timePref?.trim() || null,
    memberType: params.demographics?.memberType || null,
    personalId: params.demographics?.personalId?.trim() || null,
    pool: params.demographics?.pool?.trim() || null,
  };

  const metaPayload = {
    equipment: {
      hasPack,
      articles: normArticles,
      rawText: params.equipment?.rawText || null,
      size: params.equipment?.size?.trim() || null,
      notes: params.equipment?.notes?.trim() || null,
    },
    demographics: cleanDemo,
  };

  // Build human-readable summary for legacy readers/raw views
  const humanParts: string[] = [];

  if (cleanDemo.memberType === "old") {
    humanParts.push(`Renouvellement Ancien Membre${cleanDemo.personalId ? ` (ID: ${cleanDemo.personalId})` : ""}`);
  }
  if (cleanDemo.pool) {
    humanParts.push(`Piscine: ${cleanDemo.pool}`);
  }
  if (hasPack) {
    if (normArticles.length > 0) {
      const labels = normArticles.map(getArticleShortLabel).join(", ");
      humanParts.push(`Pack Equipement: ${labels}`);
    } else {
      humanParts.push("Pack Equipement: Oui");
    }
  }
  if (cleanDemo.city) {
    humanParts.push(`Ville: ${cleanDemo.city}`);
  }
  if (cleanDemo.age) {
    humanParts.push(`Age: ${cleanDemo.age}`);
  }
  if (cleanDemo.whatsapp) {
    humanParts.push(`WhatsApp: ${cleanDemo.whatsapp}`);
  }
  if (cleanDemo.channel) {
    const ch = cleanDemo.channelOther ? `${cleanDemo.channel} (${cleanDemo.channelOther})` : cleanDemo.channel;
    humanParts.push(`Canal: ${ch}`);
  }
  if (cleanDemo.goal) {
    humanParts.push(`Objectif: ${cleanDemo.goal}`);
  }
  if (cleanDemo.timePref) {
    humanParts.push(`Creneau: ${cleanDemo.timePref}`);
  }

  const metaString = `[AQA_META_START]${JSON.stringify(metaPayload)}[AQA_META_END]`;
  const summaryString = humanParts.length > 0 ? `[DETAILS_SUMMARY: ${humanParts.join(" | ")}]` : "";
  const freeNotes = params.userNotes?.trim() || "";

  // Combine elements: Meta tag first, summary block, then user's free-form notes
  const combined = [metaString, summaryString, freeNotes].filter(Boolean).join("\n");
  return combined;
}
