export interface HommeRosterEntry {
  originalNum: string;
  fullName: string;
  category: string;
  level: string;
  formula: string;
  duration: string;
  phone: string;
  dateOfStart: string;
  paymentStatus: string;
  groupStatus: string;
  notes: string;
}

export const HOMME_ROSTER_DATA: HommeRosterEntry[] = [
  {
    "originalNum": "1",
    "fullName": "Ahmed Agoumadaz",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-08-31T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #1 (members) | Original date: 2025-08-31"
  },
  {
    "originalNum": "2",
    "fullName": "Abdelmadjid Salhi",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-01T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #2 (members) | Original date: 2025-09-01"
  },
  {
    "originalNum": "3",
    "fullName": "Mohamed Salhi",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-01T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #3 (members) | Original date: 2025-09-01"
  },
  {
    "originalNum": "4",
    "fullName": "Omar Rezig",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-02T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #4 (members) | Original date: 2025-09-02"
  },
  {
    "originalNum": "5",
    "fullName": "Mustapha Kechadi",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-02T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #5 (members) | Original date: 2025-09-02"
  },
  {
    "originalNum": "6",
    "fullName": "Zidane Makhaneg",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-03T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #6 (members) | Original date: 2025-09-03"
  },
  {
    "originalNum": "7",
    "fullName": "Khaled Fedag",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-03T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #7 (members) | Original date: 2025-09-03"
  },
  {
    "originalNum": "8",
    "fullName": "Ouzine Fidir",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-03T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #8 (members) | Original date: 2025-09-03"
  },
  {
    "originalNum": "9",
    "fullName": "Abdelghani Mamouni",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-10T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #9 (members) | Original date: 2025-09-10"
  },
  {
    "originalNum": "10",
    "fullName": "Mohand Boukherouf",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-05T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #10 (members) | Original date: 2025-09-05"
  },
  {
    "originalNum": "11",
    "fullName": "Yacine Abzar",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-05T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #11 (members) | Original date: 2025-09-05"
  },
  {
    "originalNum": "12",
    "fullName": "Nassim Rabhi",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-06T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #12 (members) | Original date: 2025-09-06"
  },
  {
    "originalNum": "13",
    "fullName": "Rassim Rabhi",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-06T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #13 (members) | Original date: 2025-09-06"
  },
  {
    "originalNum": "14",
    "fullName": "Ali Marzen",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-08T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #14 (members) | Original date: 2025-09-08"
  },
  {
    "originalNum": "15",
    "fullName": "Youcef Ben Ahsen",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-08T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #15 (members) | Original date: 2025-09-08"
  },
  {
    "originalNum": "16",
    "fullName": "Bencherki Djahafi",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-09T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #16 (members) | Original date: 2025-09-09"
  },
  {
    "originalNum": "17",
    "fullName": "Amer Bouguendoura",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-11T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #17 (members) | Original date: 2025-09-11"
  },
  {
    "originalNum": "18",
    "fullName": "Mohamed Rahim",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-12T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #18 (members) | Original date: 2025-09-12"
  },
  {
    "originalNum": "19",
    "fullName": "Slimane Mouelhi",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-13T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #19 (members) | Original date: 2025-09-13"
  },
  {
    "originalNum": "20",
    "fullName": "Abdelaziz Abdelkrim",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-19T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #20 (members) | Original date: 2025-09-19"
  },
  {
    "originalNum": "21",
    "fullName": "Elbachir Berkas",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-10T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #21 (members) | Original date: 2025-09-10"
  },
  {
    "originalNum": "22",
    "fullName": "Noureddine Berkas",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-10T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #22 (members) | Original date: 2025-09-10"
  },
  {
    "originalNum": "23",
    "fullName": "Abdelhamid Hamoudi",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-10-05T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #23 (members) | Original date: 2025-10-05"
  },
  {
    "originalNum": "24",
    "fullName": "Karim Bakhti",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-10-05T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #24 (members) | Original date: 2025-10-05"
  },
  {
    "originalNum": "25",
    "fullName": "Nabil Arkak",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-10-07T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #25 (members) | Original date: 2025-10-07"
  },
  {
    "originalNum": "26",
    "fullName": "Mourad Faradji",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-10-08T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #26 (members) | Original date: 2025-10-08"
  },
  {
    "originalNum": "27",
    "fullName": "Abdelhamid Brich",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-10-15T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #27 (members) | Original date: 2025-10-15"
  },
  {
    "originalNum": "28",
    "fullName": "Imad Touadji",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2023-09-12T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #28 (members) | Original date: 2023-09-12"
  },
  {
    "originalNum": "48",
    "fullName": "Hassan Radjai",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2026-02-01T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #48 (members) | Original date: 2026-02-01"
  },
  {
    "originalNum": "49",
    "fullName": "Anis Ben Rabie",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2026-01-04T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #49 (members) | Original date: 2026-01-04"
  },
  {
    "originalNum": "50",
    "fullName": "Rayane Boudghezdam",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2026-04-04T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #50 (members) | Original date: 2026-04-04"
  },
  {
    "originalNum": "51",
    "fullName": "Said Merdjani",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2026-04-04T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #51 (members) | Original date: 2026-04-04"
  },
  {
    "originalNum": "52",
    "fullName": "Abdelghani Younsi",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-01T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #52 (members) | Original date: Not specified (defaulted to 2025-09-01)"
  },
  {
    "originalNum": "53",
    "fullName": "Oussama Ben Aziz",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2026-04-22T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #53 (members) | Original date: 2026-04-22"
  },
  {
    "originalNum": "54",
    "fullName": "Djalal Mabdouaa",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-01T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #54 (members) | Original date: Not specified (defaulted to 2025-09-01)"
  },
  {
    "originalNum": "55",
    "fullName": "Nadjib Derbal",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-01T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #55 (members) | Original date: Not specified (defaulted to 2025-09-01)"
  },
  {
    "originalNum": "56",
    "fullName": "Hafid Louchate",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2026-05-21T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #56 (members) | Original date: 2026-05-21"
  },
  {
    "originalNum": "57",
    "fullName": "Ammi Ahmed",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2026-06-04T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #57 (members) | Original date: 2026-06-04"
  },
  {
    "originalNum": "58",
    "fullName": "Nadjib Yetto",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2026-01-14T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #58 (members) | Original date: 2026-01-14"
  },
  {
    "originalNum": "59",
    "fullName": "Khaled Telouah",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-01T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #59 (members) | Original date: Not specified (defaulted to 2025-09-01)"
  },
  {
    "originalNum": "60",
    "fullName": "Abderrahmane Tabamar",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-01T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #60 (members) | Original date: Not specified (defaulted to 2025-09-01)"
  },
  {
    "originalNum": "61",
    "fullName": "Mohamed Nasser",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-10-13T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #61 (members) | Original date: 2025-10-13"
  },
  {
    "originalNum": "62",
    "fullName": "Chakib Hafid",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2026-06-01T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #62 (members) | Original date: 2026-06-01"
  },
  {
    "originalNum": "63",
    "fullName": "Khaled Bousaid",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2026-06-02T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #63 (members) | Original date: 2026-06-02"
  },
  {
    "originalNum": "64",
    "fullName": "Bilal Bousaid",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2026-06-02T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #64 (members) | Original date: 2026-06-02"
  },
  {
    "originalNum": "65",
    "fullName": "Abdelmadjid Khoukhi",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2026-06-08T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #65 (members) | Original date: 2026-06-08"
  },
  {
    "originalNum": "66",
    "fullName": "Abdelkrim Cherif",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-01T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #66 (members) | Original date: Not specified (defaulted to 2025-09-01)"
  },
  {
    "originalNum": "67",
    "fullName": "Mokrane Nabti",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-01-31T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #67 (members) | Original date: 2025-01-31"
  },
  {
    "originalNum": "68",
    "fullName": "Mohamed Amine Boudouha",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2026-06-17T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #68 (members) | Original date: 2026-06-17"
  },
  {
    "originalNum": "69",
    "fullName": "Reda Boulouiza",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-01T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #69 (members) | Original date: Not specified (defaulted to 2025-09-01)"
  },
  {
    "originalNum": "70",
    "fullName": "Walid Lamouchi",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2026-06-17T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #70 (members) | Original date: 2026-06-17"
  },
  {
    "originalNum": "71",
    "fullName": "Abdelillah Si Mohamed",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-01T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #71 (members) | Original date: Not specified (defaulted to 2025-09-01)"
  },
  {
    "originalNum": "73",
    "fullName": "Salah Aadouka",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2026-06-28T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #73 (members) | Original date: 2026-06-28"
  },
  {
    "originalNum": "74",
    "fullName": "Ramzi Laakoun",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2026-07-04T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #74 (members) | Original date: 2026-07-04"
  },
  {
    "originalNum": "75",
    "fullName": "Marouane LLM",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2026-07-05T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #75 (members) | Original date: 2026-07-05"
  },
  {
    "originalNum": "76",
    "fullName": "Ahcene Hamouche",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2026-04-16T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #76 (members) | Original date: 2026-04-16"
  },
  {
    "originalNum": "77",
    "fullName": "Moulaud Hamizi",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-04-09T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #77 (members) | Original date: 2025-04-09"
  },
  {
    "originalNum": "78",
    "fullName": "Loai Elkeria",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-01T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #78 (members) | Original date: Not specified (defaulted to 2025-09-01)"
  },
  {
    "originalNum": "86",
    "fullName": "Abdelkader Abdellaoui",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-09T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #86 (members) | Original date: 2025-09-09"
  },
  {
    "originalNum": "87",
    "fullName": "Mohamed Ben Ayad",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-11-27T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #87 (members) | Original date: 2025-11-27"
  },
  {
    "originalNum": "89",
    "fullName": "Ahmed Rabia",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2026-05-03T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #89 (members) | Original date: 2026-05-03"
  },
  {
    "originalNum": "90",
    "fullName": "Ezzeddine Mokrane",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-06T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #90 (members) | Original date: 2025-09-06"
  },
  {
    "originalNum": "91",
    "fullName": "Ezzouhir Zerkouk",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2026-06-22T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #91 (members) | Original date: 2026-06-22"
  },
  {
    "originalNum": "93",
    "fullName": "Amine",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2026-06-22T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #93 (members) | Original date: 2026-06-22"
  },
  {
    "originalNum": "95",
    "fullName": "Hicham Bounab",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-03T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #95 (members) | Original date: 2025-09-03"
  },
  {
    "originalNum": "1",
    "fullName": "Walid Saidi",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-08-23T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #1 (waitlist) | Original date: 2025-08-23"
  },
  {
    "originalNum": "2",
    "fullName": "Nadhim Saidi",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-01T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #2 (waitlist) | Original date: Not specified (defaulted to 2025-09-01)"
  },
  {
    "originalNum": "3",
    "fullName": "Ouanass Naouasria",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-01T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #3 (waitlist) | Original date: 2025-09-01"
  },
  {
    "originalNum": "4",
    "fullName": "Marouane Danane",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-02T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #4 (waitlist) | Original date: 2025-09-02"
  },
  {
    "originalNum": "5",
    "fullName": "Noureddine Moussaoui",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-04T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #5 (waitlist) | Original date: 2025-09-04"
  },
  {
    "originalNum": "6",
    "fullName": "Brahim Amroush",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-04T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #6 (waitlist) | Original date: 2025-09-04"
  },
  {
    "originalNum": "7",
    "fullName": "Abdennour Hamouda",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-04T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #7 (waitlist) | Original date: 2025-09-04"
  },
  {
    "originalNum": "8",
    "fullName": "Bilal Boumezyane",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-05T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #8 (waitlist) | Original date: 2025-09-05"
  },
  {
    "originalNum": "9",
    "fullName": "Amine Karmous",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-27T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #9 (waitlist) | Original date: 2025-09-27"
  },
  {
    "originalNum": "10",
    "fullName": "Allal Mizanine",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-05T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #10 (waitlist) | Original date: 2025-09-05"
  },
  {
    "originalNum": "11",
    "fullName": "Nadjah Kziz",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-10T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #11 (waitlist) | Original date: 2025-09-10"
  },
  {
    "originalNum": "12",
    "fullName": "Youcef Sahban",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-10-08T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #12 (waitlist) | Original date: 2025-10-08"
  },
  {
    "originalNum": "13",
    "fullName": "Adel Chamseddine",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-08-27T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #13 (waitlist) | Original date: 2025-08-27"
  },
  {
    "originalNum": "18",
    "fullName": "Abdelhak Bousalem",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2026-04-01T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #18 (waitlist) | Original date: 2026-04-01"
  },
  {
    "originalNum": "19",
    "fullName": "Omar Belabbas",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2026-04-11T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #19 (waitlist) | Original date: 2026-04-11"
  },
  {
    "originalNum": "20",
    "fullName": "Hakim Tazir",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-16T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #20 (waitlist) | Original date: 2025-09-16"
  },
  {
    "originalNum": "21",
    "fullName": "Ahmed Boukerdouh",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-10-02T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #21 (waitlist) | Original date: 2025-10-02"
  },
  {
    "originalNum": "22",
    "fullName": "Ahmed Boubarkaoui",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2026-01-01T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #22 (waitlist) | Original date: 2026-01-01"
  },
  {
    "originalNum": "23",
    "fullName": "Haithem Kachi",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-08-26T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #23 (waitlist) | Original date: 2025-08-26"
  },
  {
    "originalNum": "24",
    "fullName": "Ilyes Kadri",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2026-06-07T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #24 (waitlist) | Original date: 2026-06-07"
  },
  {
    "originalNum": "25",
    "fullName": "Tarek Hamouda",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-11-12T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #25 (waitlist) | Original date: 2025-11-12"
  },
  {
    "originalNum": "26",
    "fullName": "Yacine Mebarki",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2026-04-16T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #26 (waitlist) | Original date: 2026-04-16"
  },
  {
    "originalNum": "27",
    "fullName": "Oussama Khelifi",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2026-04-09T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #27 (waitlist) | Original date: 2026-04-09"
  },
  {
    "originalNum": "28",
    "fullName": "Bilal Hamadi",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2026-04-01T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #28 (waitlist) | Original date: 2026-04-01"
  },
  {
    "originalNum": "29",
    "fullName": "Abdesslem Zeddam",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2026-02-11T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #29 (waitlist) | Original date: 2026-02-11"
  },
  {
    "originalNum": "30",
    "fullName": "Younes Khiari",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2026-02-13T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #30 (waitlist) | Original date: 2026-02-13"
  },
  {
    "originalNum": "31",
    "fullName": "Ali Seba",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-11-01T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #31 (waitlist) | Original date: 2025-11-01"
  },
  {
    "originalNum": "32",
    "fullName": "Ahmed Mohamedi",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-11-06T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #32 (waitlist) | Original date: 2025-11-06"
  },
  {
    "originalNum": "33",
    "fullName": "Amine Guermouche",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-10-01T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #33 (waitlist) | Original date: 2025-10-01"
  },
  {
    "originalNum": "34",
    "fullName": "Yacine Ayrache",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-05T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #34 (waitlist) | Original date: 2025-09-05"
  },
  {
    "originalNum": "35",
    "fullName": "Nassim Ayrache",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-05T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #35 (waitlist) | Original date: 2025-09-05"
  },
  {
    "originalNum": "36",
    "fullName": "Yasser Kalloune",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-11T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #36 (waitlist) | Original date: 2025-09-11"
  },
  {
    "originalNum": "37",
    "fullName": "Chouaib Seksaoui",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-12-05T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #37 (waitlist) | Original date: 2025-12-05"
  },
  {
    "originalNum": "38",
    "fullName": "Abderrahmane Achou",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2026-01-01T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #38 (waitlist) | Original date: 2026-01-01"
  },
  {
    "originalNum": "39",
    "fullName": "Laayadi Louznadji",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-08-25T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #39 (waitlist) | Original date: 2025-08-25"
  },
  {
    "originalNum": "40",
    "fullName": "Abdelkrim Hanichad",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2026-04-04T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #40 (waitlist) | Original date: 2026-04-04"
  },
  {
    "originalNum": "41",
    "fullName": "Marouane Si Hamoud",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-11-16T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #41 (waitlist) | Original date: 2025-11-16"
  },
  {
    "originalNum": "42",
    "fullName": "Moulaud Kouadri Hebbaz",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-04T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #42 (waitlist) | Original date: 2025-09-04"
  },
  {
    "originalNum": "43",
    "fullName": "Said Ben Talaa",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-10-01T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #43 (waitlist) | Original date: 2025-10-01"
  },
  {
    "originalNum": "44",
    "fullName": "Abderrezak Zouaoui",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-03T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #44 (waitlist) | Original date: 2025-09-03"
  },
  {
    "originalNum": "45",
    "fullName": "Ismail Ramdane",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-10-01T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #45 (waitlist) | Original date: 2025-10-01"
  },
  {
    "originalNum": "46",
    "fullName": "Abdelmalek Bilarbou",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-11-12T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #46 (waitlist) | Original date: 2025-11-12"
  },
  {
    "originalNum": "47",
    "fullName": "Fateh Amriaoui",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-12-13T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #47 (waitlist) | Original date: 2025-12-13"
  },
  {
    "originalNum": "48",
    "fullName": "Mohamed Ayad",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-01T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #48 (waitlist) | Original date: 2025-09-01"
  },
  {
    "originalNum": "49",
    "fullName": "Amine Letad",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-01T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #49 (waitlist) | Original date: 2025-09-01"
  },
  {
    "originalNum": "50",
    "fullName": "Abdelmadjid Mouzai",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-02T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #50 (waitlist) | Original date: 2025-09-02"
  },
  {
    "originalNum": "52",
    "fullName": "Hicham Bouguezata",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-12-03T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #52 (waitlist) | Original date: 2025-12-03"
  },
  {
    "originalNum": "53",
    "fullName": "Abdelkrim Khermimoun",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-11-16T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #53 (waitlist) | Original date: 2025-11-16"
  },
  {
    "originalNum": "54",
    "fullName": "Omar Guendouz",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-11-16T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #54 (waitlist) | Original date: 2025-11-16"
  },
  {
    "originalNum": "56",
    "fullName": "Abdennasser Ksouri",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-11-01T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #56 (waitlist) | Original date: 2025-11-01"
  },
  {
    "originalNum": "57",
    "fullName": "Abdelmadjid Si Lafdil",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-09T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #57 (waitlist) | Original date: 2025-09-09"
  },
  {
    "originalNum": "58",
    "fullName": "Mohamed Islam Bazine",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2026-05-18T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #58 (waitlist) | Original date: 2026-05-18"
  },
  {
    "originalNum": "59",
    "fullName": "Imad Boubaker",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-16T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #59 (waitlist) | Original date: 2025-09-16"
  },
  {
    "originalNum": "60",
    "fullName": "Said Belaribi",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-11-22T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #60 (waitlist) | Original date: 2025-11-22"
  },
  {
    "originalNum": "61",
    "fullName": "Saad Hamel",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-11-19T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #61 (waitlist) | Original date: 2025-11-19"
  },
  {
    "originalNum": "62",
    "fullName": "Ahmed Tazbint",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-23T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #62 (waitlist) | Original date: 2025-09-23"
  },
  {
    "originalNum": "63",
    "fullName": "Aissa Serrar",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-03T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #63 (waitlist) | Original date: 2025-09-03"
  },
  {
    "originalNum": "64",
    "fullName": "Abdelfettah Laouad",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-01T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #64 (waitlist) | Original date: 2025-09-01"
  },
  {
    "originalNum": "65",
    "fullName": "Mohamed Imrane",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-08-22T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #65 (waitlist) | Original date: 2025-08-22"
  },
  {
    "originalNum": "66",
    "fullName": "Ismail Taibi Hamani",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-08-31T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #66 (waitlist) | Original date: 2025-08-31"
  },
  {
    "originalNum": "67",
    "fullName": "Mohamed Mizanil",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-03T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #67 (waitlist) | Original date: 2025-09-03"
  },
  {
    "originalNum": "68",
    "fullName": "Youcef Brahmia",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-02T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #68 (waitlist) | Original date: 2025-09-02"
  },
  {
    "originalNum": "69",
    "fullName": "Ilyes Chiter",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-10T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #69 (waitlist) | Original date: 2025-09-10"
  },
  {
    "originalNum": "70",
    "fullName": "Abdelwahab Meziani",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-26T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #70 (waitlist) | Original date: 2025-09-26"
  },
  {
    "originalNum": "71",
    "fullName": "Fethi Chalabi",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-01T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #71 (waitlist) | Original date: Not specified (defaulted to 2025-09-01)"
  },
  {
    "originalNum": "72",
    "fullName": "Sofiane Ben Ayad",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-11-27T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #72 (waitlist) | Original date: 2025-11-27"
  },
  {
    "originalNum": "74",
    "fullName": "Faycal Zikouf",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-08-26T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #74 (waitlist) | Original date: 2025-08-26"
  },
  {
    "originalNum": "75",
    "fullName": "Yacine Salhi",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-10-18T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #75 (waitlist) | Original date: 2025-10-18"
  },
  {
    "originalNum": "76",
    "fullName": "Fares Alalou",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-08-25T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #76 (waitlist) | Original date: 2025-08-25"
  },
  {
    "originalNum": "77",
    "fullName": "Nouh Gouini",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-03T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #77 (waitlist) | Original date: 2025-09-03"
  },
  {
    "originalNum": "78",
    "fullName": "Mohamed Amine Bouakkaz",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-03T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #78 (waitlist) | Original date: 2025-09-03"
  },
  {
    "originalNum": "80",
    "fullName": "Youcef Belfkih",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-09T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #80 (waitlist) | Original date: 2025-09-09"
  },
  {
    "originalNum": "81",
    "fullName": "Abdelhak Nsili",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-10-08T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #81 (waitlist) | Original date: 2025-10-08"
  },
  {
    "originalNum": "82",
    "fullName": "Abderrahmane Boumezyane",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-12T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #82 (waitlist) | Original date: 2025-09-12"
  },
  {
    "originalNum": "83",
    "fullName": "Rabie Younes Bouamama",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-13T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #83 (waitlist) | Original date: 2025-09-13"
  },
  {
    "originalNum": "84",
    "fullName": "Ettayeb Bouamama",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-13T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #84 (waitlist) | Original date: 2025-09-13"
  },
  {
    "originalNum": "85",
    "fullName": "Abdesslem Ben Aouda",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-06T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #85 (waitlist) | Original date: 2025-09-06"
  },
  {
    "originalNum": "86",
    "fullName": "Redouane Hadjam",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-12-20T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #86 (waitlist) | Original date: 2025-12-20"
  },
  {
    "originalNum": "87",
    "fullName": "Abderraouf Ben Yakhlef",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-12-06T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #87 (waitlist) | Original date: 2025-12-06"
  },
  {
    "originalNum": "88",
    "fullName": "Kamel Aasmani",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-12-13T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #88 (waitlist) | Original date: 2025-12-13"
  },
  {
    "originalNum": "89",
    "fullName": "Mounir Aitar",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-06T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #89 (waitlist) | Original date: 2025-09-06"
  },
  {
    "originalNum": "90",
    "fullName": "Mohamed Khedraoui",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-10-02T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #90 (waitlist) | Original date: 2025-10-02"
  },
  {
    "originalNum": "91",
    "fullName": "Ismail Hakoum",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-12-04T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #91 (waitlist) | Original date: 2025-12-04"
  },
  {
    "originalNum": "92",
    "fullName": "Aymen Aichaten",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-01-04T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #92 (waitlist) | Original date: 2025-01-04"
  },
  {
    "originalNum": "93",
    "fullName": "Ahmed Zaadi",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-01-04T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #93 (waitlist) | Original date: 2025-01-04"
  },
  {
    "originalNum": "94",
    "fullName": "Islam Alalou",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-08-25T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #94 (waitlist) | Full date range: 2025-08-25 to 2026-04-02"
  },
  {
    "originalNum": "95",
    "fullName": "Hamza Alalou",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2026-04-02T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #95 (waitlist) | Original date: 2026-04-02"
  },
  {
    "originalNum": "96",
    "fullName": "Abdelkrim Marzouk",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-04T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #96 (waitlist) | Original date: 2025-09-04"
  },
  {
    "originalNum": "97",
    "fullName": "Mustapha Dabbah",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-13T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #97 (waitlist) | Original date: 2025-09-13"
  },
  {
    "originalNum": "98",
    "fullName": "Ali Hamouche",
    "category": "homme",
    "level": "new_aqa",
    "formula": "G10",
    "duration": "3m",
    "phone": "Non renseigne",
    "dateOfStart": "2025-09-14T00:00:00.000Z",
    "paymentStatus": "unpaid",
    "groupStatus": "proposed",
    "notes": "Imported roster entry #98 (waitlist) | Original date: 2025-09-14"
  }
];
